AllCops:
  TargetRubyVersion: 2.6
  DefaultFormatter: simple

Layout/IndentationWidth:
  Width: 4

Layout/LineLength:
  Max: 120

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Naming/FileName:
  Enabled: false
